Fix: docker 빌드 확인 코드 삽입

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,10 +16,16 @@ jobs:
     - name: Login to DockerHub (Optional)
       run: echo "Skipping DockerHub login since we're saving as tar."
 
-    - name: Docker Build
+    # - name: Docker Build
+    #   run: |
+    #     docker build -t nextjs-app .
+    #     docker save nextjs-app -o nextjs-app.tar
+
+    - name: Check .next after build
       run: |
         docker build -t nextjs-app .
-        docker save nextjs-app -o nextjs-app.tar
+        docker run --rm --entrypoint "" nextjs-app ls -al /app/.next || echo ".next not found"
+
 
     - name: Package artifacts (tar + appspec.yml + scripts)
       run: |
